<?php
    require './h2o.php';
    require './session.php';
    $h2o = new h2o('templates/lista-nozze-riempita.html');
    echo $h2o->render(array('DEBUG_ENABLE'=>False,
        'charset' => 'UTF-8',
        'pagina' => 'lista-nozze',
        'imageBaseUrl' => './static/img/viaggio/',
        'objList' => array(
            array(
                'row' =>  '1',
                'column' =>  '1',
                'file' =>  './Giappone/geisha.jpg',
                'width' =>  '180',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br/> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '1',
                'column' =>  '1',
                'file' =>  './Giappone/hakone.jpg',
                'width' =>  '270',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '1',
                'column' =>  '1',
                'file' =>  './Giappone/img02.jpg',
                'width' =>  '320',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '2',
                'column' =>  '1',
                'file' =>  './Giappone/img04_tokyo.jpg',
                'width' =>  '320',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '2',
                'column' =>  '1',
                'file' =>  './Giappone/img06_kyoto.jpg',
                'width' =>  '320',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '2',
                'column' =>  '1',
                'file' =>  './Giappone/img08.jpg',
                'width' =>  '270',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '3',
                'column' =>  '1',
                'file' =>  './Giappone/kanazawa3.jpg',
                'width' =>  '269',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '3',
                'column' =>  '1',
                'file' =>  './Giappone/kyoto.jpg',
                'width' =>  '240',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '3',
                'column' =>  '1',
                'file' =>  './Giappone/lanterne.jpg',
                'width' =>  '240',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '4',
                'column' =>  '1',
                'file' =>  './Giappone/miyajima.jpg',
                'width' =>  '240',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '4',
                'column' =>  '1',
                'file' =>  './Giappone/nikko9.jpg',
                'width' =>  '271',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '4',
                'column' =>  '1',
                'file' =>  './Giappone/shirakawago.jpg',
                'width' =>  '268',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '5',
                'column' =>  '1',
                'file' =>  './Giappone/takayama.jpg',
                'width' =>  '266',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '5',
                'column' =>  '1',
                'file' =>  './Giappone/takayama1.jpg',
                'width' =>  '270',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '5',
                'column' =>  '1',
                'file' =>  './Giappone/tokyo.jpg',
                'width' =>  '288',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '6',
                'column' =>  '1',
                'file' =>  './Giappone/villaggioHida_takayama.jpg',
                'width' =>  '241',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '6',
                'column' =>  '1',
                'file' =>  './Thailandia/Koh-Phi-Phi-the-beach.jpg',
                'width' =>  '272',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '6',
                'column' =>  '1',
                'file' =>  './Thailandia/Koh-Samui-palm-fringed-beach-300x224.jpg',
                'width' =>  '241',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '7',
                'column' =>  '1',
                'file' =>  './Thailandia/Koh-Samui-palm-tree-hammock.jpg',
                'width' =>  '240',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '7',
                'column' =>  '1',
                'file' =>  './Thailandia/Koh-Samui.jpg',
                'width' =>  '389',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '7',
                'column' =>  '1',
                'file' =>  './Thailandia/Koh-Tao-beach-Thailand.jpg',
                'width' =>  '288',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '8',
                'column' =>  '1',
                'file' =>  './Thailandia/Koh_Samui_Lipa_Noi2.jpg',
                'width' =>  '240',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '8',
                'column' =>  '1',
                'file' =>  './Thailandia/thailand-full.jpg',
                'width' =>  '270',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '8',
                'column' =>  '1',
                'file' =>  './Thailandia/turtle1.jpg',
                'width' =>  '240',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
            array(
                'row' =>  '9',
                'column' =>  '1',
                'file' =>  './Thailandia/yenitpic13.png',
                'width' =>  '286',
                'height' =>  '180',
                'alternate' => '',
                'title' => 'Info Lista',
                'body' => 'Agenzia di viaggio Follie Viaggi.<br> IBAN: 6153723527<br> ',
            ),
        ),
    ));
?>
